version: "3"
services:
  # clash core
  clash:
    image: dreamacro/clash-premium
    restart: always
    volumes:
      - /opt/clash:/root/.config/clash
    container_name: clash
    ports:
      - "7890:7890"
      - "7891:7891"
      - "9090:9090"
  # clash dashboard
  yacd:
    image: haishanh/yacd
    restart: always
    depends_on:
      - clash
    ports:
      - "7892:80"
    container_name: yacd
  # clash subscribe update service
  sub2clash:
    image: cheerchen37/sub2clash
    restart: always
    volumes:
      - /opt/clash:/configs
    depends_on:
      - clash
    ports:
      - "7893:80"
    environment:
      CLASH_CONTROLLER: "192.168.0.110:9091"
      SUB_WHITELIST: "日本,香港,美国,HK,JP,US"
      SUB_BLACKLIST: "仅海外,回国,V1,游戏,广州"
      SUB_URLS: ""
      CRON: "*/30 * * * *"
    container_name: sub2clash
