port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: debug
external-controller: ':9090'
dns:
  enable: true
  listen: '0.0.0.0:53'
  ipv6: false
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
  fallback:
    - 1.1.1.1 # cloudflare DNS UDP
    - 8.8.8.8 # Google DNS UDP
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4

proxies: null

proxy-groups:
  - name: SELECT
    type: select
    proxies:
      - UT
      - JP
      - HK
      - US
      - DIRECT
  - url: 'https://www.gstatic.com/generate_204'
    interval: 1800
    name: UT
    type: url-test
    proxies:
      - all
  - url: 'https://www.gstatic.com/generate_204'
    interval: 1800
    name: JP
    type: url-test
    proxies:
      - jp
  - url: 'https://www.gstatic.com/generate_204'
    interval: 1800
    name: HK
    type: url-test
    proxies:
      - hk
  - url: 'https://www.gstatic.com/generate_204'
    interval: 1800
    name: US
    type: url-test
    proxies:
      - us

rules:
  - 'DOMAIN-SUFFIX,local,DIRECT'
  - 'IP-CIDR,192.168.0.0/16,DIRECT'
  - 'IP-CIDR,127.0.0.0/8,DIRECT'
  - 'IP-CIDR,172.16.0.0/12,DIRECT'
  - 'IP-CIDR,10.0.0.0/8,DIRECT'
  - 'IP-CIDR,17.0.0.0/8,DIRECT'
  - 'IP-CIDR,100.64.0.0/10,DIRECT'
  - 'DOMAIN-SUFFIX,jp,JP'
  - 'DOMAIN-KEYWORD,dmm,JP'
  - 'DOMAIN-KEYWORD,binance,JP'
  - 'GEOIP,JP,JP'
  - 'DOMAIN-KEYWORD,google,HK'
  - 'DOMAIN-KEYWORD,oculus,HK'
  - 'DOMAIN-KEYWORD,facebook,HK'
  - 'DOMAIN-KEYWORD,hentai,HK'
  - 'DOMAIN-KEYWORD,konachan,HK'
  - 'GEOIP,HK,HK'
  - 'DOMAIN-KEYWORD,musicbrainz,HK'
  - 'DOMAIN-KEYWORD,openai,JP'
  - 'DOMAIN-KEYWORD,twitter,JP'
  - 'DOMAIN-KEYWORD,twimg,JP'
  - 'GEOIP,US,HK'
  - 'GEOIP,CN,DIRECT'
  - 'MATCH,SELECT'

Proxy: null
ProxyGroup: null
Rule: null
